FROM pveber/bistro-base:latest

RUN apt-get update && apt-get install -y bowtie=1.1.2-4 \
                                         bowtie2=2.2.9-2 \
                                         tophat=2.1.1+dfsg-2
