type bam = Types.bam
class type bed3 = Types.bed3
class type bed4 = Types.bed4
class type bed5 = Types.bed5
type fasta = Types.fasta
class type gff = Types.gff
type 'a fastq = 'a Types.fastq
type sam = Types.sam
type sra = Types.sra

(* module Bed = Bed *)
module Bowtie = Bowtie
(* module Bowtie2 = Bowtie2 *)
(* module Deseq2 = Deseq2 *)
(* module Ensembl = Ensembl *)
(* module FastQC = FastQC *)
(* module Fastq = Fastq *)
(* module Htseq = Htseq *)
(* module Jaspar = Jaspar *)
(* module Macs = Macs *)
module Macs2 = Macs2
(* module Meme_suite = Meme_suite *)
module Samtools = Samtools
(* module Sra = Sra *)
module Sra_toolkit = Sra_toolkit
(* module Tophat = Tophat *)
module Ucsc_gb = Ucsc_gb
