type bam = Defs.bam
class type bed3 = Defs.bed3
class type bed4 = Defs.bed4
class type bed5 = Defs.bed5
class type bed6 = Defs.bed6
type fasta = Defs.fasta
class type gff = Defs.gff
type 'a fastq = 'a Defs.fastq
type sam = Defs.sam
type sra = Defs.sra

module Bed = Bed
module Bedtools = Bedtools
module Bowtie = Bowtie
module Bowtie2 = Bowtie2
module Deeptools = Deeptools
module Deseq2 = Deseq2
module Ensembl = Ensembl
module Fastq = Fastq
module Fastq_screen = Fastq_screen
module FastQC = FastQC
module Htseq = Htseq
(* module Jaspar = Jaspar *)
module Macs = Macs
module Macs2 = Macs2
module Meme_suite = Meme_suite
module Samtools = Samtools
module Sra = Sra
module Sra_toolkit = Sra_toolkit
module Srst2 = Srst2
module Tophat = Tophat
module Ucsc_gb = Ucsc_gb
