type bam = Defs.bam
class type bed3 = Defs.bed3
class type bed4 = Defs.bed4
class type bed5 = Defs.bed5
type fasta = Defs.fasta
class type gff = Defs.gff
type 'a fastq = 'a Defs.fastq
type sam = Defs.sam
type sra = Defs.sra

module Bed = Bed
module Bedtools = Bedtools
module Bowtie = Bowtie
module Bowtie2 = Bowtie2
module Deseq2 = Deseq2
module Ensembl = Ensembl
module FastQC = FastQC
module Fastq = Fastq
module Htseq = Htseq
(* module Jaspar = Jaspar *)
(* module Macs = Macs *)
module Macs2 = Macs2
module Meme_suite = Meme_suite
module Samtools = Samtools
module Sra = Sra
module Sra_toolkit = Sra_toolkit
module Tophat = Tophat
module Ucsc_gb = Ucsc_gb
